# ~/.config/helix/config.toml
[keys.normal]
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"

[keys.insert]
j = { k = "normal_mode" }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
